### ISSUE TITLE
Reproducible Assertion `E>=_mass' failed. 

### ISSUE THREAD

**Issue by luketpickering** [NuWro/nuwro#24]
For 21.09.1 I am seeing:

```nuwro: src/particle.h:227: void particle::set_energy(double): Assertion `E>=_mass' failed.```

when running the [params.txt](https://github.com/NuWro/nuwro/files/8614570/params.txt)

This was created as a minimum modification to exhibit failure, it is the default params.txt from data/params.txt with these two lines appended:

```
@beam/T2Knumub.txt
@target/CH.txt
```

FWIW my aim is to run with the official T2K flux root histograms and `beam_type=5`, but I wanted to showcase the failure mode with minimal extra inputs.

**Comment by luketpickering** [comment]
Here is a debug build stack trace:

```#4  0x0000000000461b27 in particle::set_energy (this=0x7ffd15cc11f0, E=1182.7622511832114) at src/particle.h:227
#5  0x00000000004b6088 in kaskada::prepare_particles (this=0x7ffd15cc1760) at src/kaskada7.cc:152
#6  0x00000000004b5619 in kaskada::kaskadaevent (this=0x7ffd15cc1760) at src/kaskada7.cc:43
#7  0x0000000000483f19 in NuWro::finishevent (this=0xe00ac0 <nuwro>, e=0x2e49e30, p=...) at src/nuwro.cc:513
#8  0x000000000048691d in NuWro::real_events (this=0xe00ac0 <nuwro>, p=...) at src/nuwro.cc:841
#9  0x0000000000488088 in NuWro::main (this=0xe00ac0 <nuwro>, argc=3, argv=0x7ffd15cc2528) at src/nuwro.cc:1006
#10 0x00000000004d12cb in main (argc=3, argv=0x7ffd15cc2528) at src/main.cc:34```

And it seems to happen on hyp events, so can reach it faster by:

```dyn_qel_cc =0      // Quasi elastic charged current
dyn_qel_nc =0      // Quasi elastic neutral current
dyn_res_cc =0      // Resonant charged current
dyn_res_nc =0      // Resonant neutral current
dyn_dis_cc =0      // Deep inelastic charged current
dyn_dis_nc =0      // Deep inelastic neutral current
dyn_coh_cc =0      // Coherent charged current
dyn_coh_nc =0      // Coherent neutral current
dyn_mec_cc =0      // Meson exchange charged current
dyn_mec_nc =0      // Meson exchange neutral current
dyn_hyp_cc =1      // Quasi elastic hyperon production
dyn_lep    =0      // Neutrino-electron
```

for now I will disable hyp locally.
